---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    NODE_ENV: production
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_PORT: 5432
    TYPEORM_ENTITIES: "./modules/domain/**/entities/*.entity.js"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 60
        timeout: 600


    - name: "install python for Ansible."
      # Your code here
      become: yes
      apt:
        name: "python3-pip"
        update_cache: yes
        state: present


  roles:
    - configure-server
    - configure-prometheus-node-exporter

